version: '3.3'

volumes:
  postgres_data:
  django_static:
  nginx:

services:

  db:
    image: postgres:13.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  yamdb:
    image: lexlibman/yamdb_final:latest
    restart: always
    volumes:
      - django_static:/static/
      - nginx:/code/nginx/
    ports:
      - "5002:5002"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.5-alpine
    restart: always
    volumes:
      - django_static:/static/
      - nginx:/etc/nginx/conf.d/
    ports:
      - "5003:5003"
    depends_on:
      - yamdb
    env_file:
      - ./.env