version: '3.3'

volumes:
  postgres_data:
  static_volume:

services:

  db:
    image: postgres:13.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  yamdb:
    image: lexlibman/yamdb_final:latest
    restart: always
    expose:
      - 8000
    volumes:
      - ./static_volume:/code/static
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./static_volume:/code/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 10080:80
      - 10443:443
    depends_on:
      - yamdb