version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    image: nginx:1.19.7
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/code/static
      - static_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web
