version: '3.3'

volumes:
  postgres_data:
  static_data:
  media_data:
  nginx_config:

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: lexlibman/yamdb_final:latest
    container_name: web
    restart: always
    volumes:
      - static_data:/code/static
      - nginx_conf:/code/nginx/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.5-alpine
    restart: always
    container_name: nginx
    volumes:
      - static_data:/code/static
      - nginx_conf:/etc/nginx/conf.d/
    ports:
      - 5000:80
    depends_on:
      - web
    env_file:
      - ./.env