version: '3.3'

volumes:
  postgres_data:
  static_volume:

services:

  db:
    image: postgres:13.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  yamdb:
    image: lexlibman/yamdb_final:latest
    restart: always
    volumes:
      - ./static_volume:/code/static/
      - ./media:/code/media/
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.19.5-alpine
    restart: always
    volumes:
      - ./static_volume:/code/static/
      - ./media:/code/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - yamdb